; 1. package size
package = 2OCTET package_part "/" package_part
package_part = 1*255(ASCII / "-")

size = 4OCTET
kind = kind_ok / kind_not_supported / kind_error
flags = OCTET

kind_ok = %x00
kind_not_supported = %x01
kind_error = %x02
kind_bad = %x03

; 1. size of the description
; 2. description
response_error = kind_error OCTET 1*255OCTET
response_bad = kind_bad OCTET 1*255OCTET

version = %x01

; 1. size of the key
; 2. key encoded in DER
hello_request = %x00 version
hello_response_ok = kind_ok
hello_response_not_supported = kind_not_supported

; 1. number of parts
; 2. file size
; 3. sha3-256 checksum of the file
; 4. length of filename
; 5. filename
upload_request = %x01 flags OCTET 4OCTET 32OCTET OCTET 1*255OCTET
upload_response_ok = kind_ok
upload_response_not_supported = kind_not_supported

; 1. part number
; 2. size of file content
; 3. file content
upload_part_request = %x02 OCTET 2OCTET 1*65536OCTET
upload_response_ok = kind_ok

; 1. number of packages to modify
list_package = OCTET 1*255package

add_package_request = %x10 list_package
add_package_response_ok = kind_ok

remove_package_request = %x11 list_package
remove_package_response_ok = kind_ok

list_package_request = %x12
; 1. number of packages
list_package_response_ok = kind_ok 4OCTET *package

build_package_request = %x13 list_package
build_package_response = kind_ok

update_world_request = %x14
update_world_response = kind_ok
