port = 2020
max_request_size = 1024  #  in Kio
data_folder = "/var/lib/portage-builder/"
users_folder = "users"  #  in the data_folder
stage3 = "https://distfiles.gentoo.org/releases/amd64/autobuilds/20260610T214636Z/stage3-amd64-openrc-20260610T214636Z.tar.xz"

[keys.root]
cert = "/etc/portage-builderd/keys/root.pem"
private_key = "/etc/portage-builderd/keys/root.key"

[keys.server]
cert = "/etc/portage-builderd/keys/server.pem"
private_key = "/etc/portage-builderd/keys/server.key"
